websocket:
  scheduled-cron: 0/30 * * * * ?
  thread-pool:
    core-pool-size: 2
    max-pool-size: 8
    queue-capacity: 1024
    thread-pool-name-prefix: Websocket-Server-AsyncScheduled-ThreadPool-
  message:
    text-message-buffer-size: 10240000
    binary-message-buffer-size: 512000000
    async-send-timeout: 30000
  session:
    idle-timeout: 1800000
  heartbeat:
    # 连续多久没有接收到心跳包，则判定Websocket Client已经断线,默认为30秒(单位:毫秒)
    not-receive-ping-max-interval: 30000

audio:
  sample-rate: 16000
  model-path: E:/git_workspace/vosk_test/src/main/resources/vosk-model-cn-0.22/
  temp-output-path: E:/git_workspace/live-voice-recognition/temp/